"""Home Affairs, Explained — conversational guidance chatbot.

Classifies which of 4 Home Affairs services a message is about, asks
branching questions one at a time, and returns a checklist built ONLY from
backend/data/home_affairs_reference.json and backend/data/document_sources.json.
Never invents a document, fee, or fact that isn't in those files.

Matches backend/api/routes.py's binding contract: routes.py looks for one
of get_guidance/handle_chat/chat/answer at import time and binds to
whichever exists, calling it as fn(message, location_dict_or_none,
conversation_id) -> dict shaped {reply, documentsNeeded, estimatedCost,
estimatedTime, nearestBranch, conversationId}. No further routes.py changes
are needed for this module to take over from the existing _chat_stub()
placeholder there (kept in place as the fallback if this module is
unavailable/broken — see routes.py's try/except around _home_affairs_fn()).

GROQ IN THE LOOP — classification and phrasing only, never facts
------------------------------------------------------------------
Groq does exactly two narrow jobs, both constrained and both with a
deterministic fallback if they fail or produce something unvalidated:

  1. CLASSIFICATION (_groq_classify_single / _groq_classify_multiple, used
     by _resolve_service / _resolve_sub_case / _resolve_situation /
     _resolve_complications): temperature 0, JSON-mode structured output,
     given ONLY the exact ids+labels pulled live from
     home_affairs_reference.json as the valid answer set. Any output that
     isn't one of those exact ids (or the explicit 'unclear' escape hatch)
     is rejected and treated as a classification failure — never used.
     On rejection, an API error, or a missing API key, classification
     falls back to the original keyword matchers (_classify_service etc.,
     kept below, unchanged) rather than asking the user again from
     scratch.

  2. PHRASING (_groq_phrase, used by _build_final_reply): takes the exact
     checklist data already assembled from the reference JSON (documents,
     fees, cautions, disclaimers — verbatim) and asks Groq only to
     rephrase it warmly. The prompt explicitly forbids adding any fact not
     in that payload. This is still checked, not just requested: any
     currency figure ("R<number>") in Groq's phrased text must already
     appear in the grounding payload passed to it
     (_phrasing_is_grounded), or the phrasing is discarded and the
     deterministic template is used instead. documentsNeeded itself is
     NEVER passed through Groq — it's always rendered directly from the
     reference JSON by _format_document_line, regardless of whether
     phrasing succeeds.

Neither call ever runs without its constraining system prompt and
reference-derived data attached — there is no "general knowledge" mode.

CONVERSATION STATE
-------------------
Sessions are keyed by conversationId (backend/api/routes.py's ChatRequest
field, generated by the frontend once per chat and sent on every turn — see
frontend/src/screens/ChatbotScreen.tsx). Two different conversationIds are
completely isolated from each other. A missing conversationId degrades
safely to a fresh, single-turn-only session (a random key per call) rather
than falling back to a shared key, so concurrent callers can never collide.
"""

from __future__ import annotations

import json
import logging
import os
import re
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

try:
    from groq import Groq
except ImportError:  # pragma: no cover - exercised only if the package is missing
    Groq = None  # type: ignore[assignment,misc]

logger = logging.getLogger(__name__)

DATA_DIR = Path(__file__).resolve().parents[1] / "data"
REFERENCE_PATH = DATA_DIR / "home_affairs_reference.json"
SOURCES_PATH = DATA_DIR / "document_sources.json"

_GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
_GROQ_TIMEOUT_SECONDS = 8.0


def load_reference() -> dict[str, Any]:
    """Load the service/decision-tree reference data. Not cached at import
    so tests can monkeypatch REFERENCE_PATH, matching identity_checker.py's
    load_records() convention."""
    with open(REFERENCE_PATH, encoding="utf-8") as f:
        return json.load(f)


def load_sources() -> dict[str, Any]:
    """Load the shared document-sources lookup (affidavit, certified copy,
    court order, etc.)."""
    with open(SOURCES_PATH, encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Conversation state, keyed by conversationId
# ---------------------------------------------------------------------------


@dataclass
class ConversationState:
    service_id: str | None = None
    sub_case_id: str | None = None
    situation_id: str | None = None  # only used for smart_id renewal_or_replacement
    complications: set[str] = field(default_factory=set)
    stage: str = "service"  # service -> sub_case -> situation? -> complications -> awaiting_complications_answer -> done


_SESSIONS: dict[str, ConversationState] = {}


def _session_key(conversation_id: str | None) -> str:
    if conversation_id:
        return f"conv:{conversation_id}"
    # No id supplied: degrade to an isolated one-off session (never a
    # shared key) so concurrent callers without an id can't collide.
    return f"conv:anonymous:{uuid.uuid4()}"


def reset_sessions() -> None:
    """Clear all in-memory conversation state. Used by tests between cases."""
    _SESSIONS.clear()


# ---------------------------------------------------------------------------
# Deterministic classification — the fallback layer. Rule-based keyword
# matching, used whenever Groq is unavailable, errors, times out, or
# returns something that fails validation against the reference JSON.
# ---------------------------------------------------------------------------

_SERVICE_KEYWORDS: dict[str, list[str]] = {
    "birth_registration": [
        "birth", "baby", "born", "newborn", "register my child", "register a birth",
    ],
    "smart_id": [
        "smart id", "id card", "identity document", "green book", "green id",
        "renew my id", "lost my id", "id book",
    ],
    "passport": ["passport", "travel document"],
    "name_surname_amendment": [
        "surname", "change my name", "name change", "maiden name",
        "spelling of my name", "fix my name", "correct my name",
    ],
}


def _classify_service(message: str) -> str | None:
    text = message.lower()
    matches = [svc for svc, keywords in _SERVICE_KEYWORDS.items() if any(kw in text for kw in keywords)]
    return matches[0] if len(matches) == 1 else None


_SUB_CASE_KEYWORDS: dict[str, dict[str, list[str]]] = {
    "birth_registration": {
        "within_30_days": [
            "within 30 days", "just born", "few days old", "this week", "recently born", "just had a baby",
        ],
        "late_registration": [
            "late", "more than 30 days", "months old", "years old", "overdue", "late registration",
        ],
    },
    "smart_id": {
        "first_application_16_plus": [
            "first id", "first time", "never had an id", "applying for the first time",
            "turning 16", "first smart id", "don't have an id", "first one", "my first", "never had one",
        ],
        "renewal_or_replacement": [
            "renew", "replace", "replacement", "lost", "stolen", "damaged", "expired",
            "green book", "already have an id",
        ],
    },
    "passport": {
        "adult": ["for myself", "i am an adult", "i'm an adult", "adult applicant"],
        "under_16": ["under 16", "younger than 16", "baby's passport", "toddler"],
        "under_18": ["under 18", "for my child", "for my son", "for my daughter", "minor"],
        "applying_abroad": ["abroad", "outside south africa", "overseas", "embassy", "consulate"],
    },
    "name_surname_amendment": {
        "spelling_error": [
            "spelling", "typo", "misspelled", "spelled wrong", "administrative error", "fix my name",
        ],
        "marriage": [
            "married", "marriage", "maiden name", "wife's surname", "husband's surname", "my wife", "my husband",
        ],
        "divorce_or_widowhood": [
            "divorce", "divorced", "widow", "widowed", "my late husband", "my late wife",
        ],
        "child_surname": [
            "my child's surname", "my son's surname", "my daughter's surname", "kid's surname", "child's name",
        ],
        "adult_unrelated_surname": [
            "assume a surname", "unrelated surname", "want to change my surname to", "take a new surname",
        ],
    },
}


def _classify_sub_case(service_id: str, message: str) -> str | None:
    text = message.lower()
    keyword_map = _SUB_CASE_KEYWORDS.get(service_id, {})
    matches = [sub_case for sub_case, keywords in keyword_map.items() if any(kw in text for kw in keywords)]
    return matches[0] if len(matches) == 1 else None


_SMART_ID_SITUATION_KEYWORDS: dict[str, list[str]] = {
    "replacing_green_id_book": ["green book", "green id book"],
    "replacing_smart_id": ["smart id card", "my smart id", "replace my card"],
    "lost_or_stolen": ["lost", "stolen"],
    "minor_applicant": ["my child", "my son", "my daughter", "minor"],
    "parent_deceased": ["parent died", "parent passed away", "parent deceased", "parent is deceased", "mother died", "father died", "is deceased"],
    "marital_status_change": ["married", "got married", "divorced"],
    "name_or_surname_amendment_pending": ["changed my name", "changed my surname", "name amendment"],
}


def _classify_smart_id_situation(message: str) -> str | None:
    text = message.lower()
    matches = [sit for sit, keywords in _SMART_ID_SITUATION_KEYWORDS.items() if any(kw in text for kw in keywords)]
    return matches[0] if len(matches) == 1 else None


_COMPLICATION_KEYWORDS: dict[str, list[str]] = {
    "birth_outside_health_facility": ["born at home", "not born in hospital", "home birth", "outside a hospital", "outside a clinic"],
    "parents_unmarried_father_to_be_recorded": ["not married", "unmarried", "father to be recorded", "acknowledge paternity"],
    "child_abandoned_orphaned_or_disputed_parentage": ["abandoned", "orphan", "orphaned", "disputed parentage", "no parents"],
    "registered_by_someone_other_than_a_parent": ["not the parent", "guardian registering", "grandparent", "relative registering"],
    "parent_deceased": ["parent died", "parent passed away", "parent deceased", "parent is deceased", "mother died", "father died", "is deceased"],
    "guardian_acting_for_applicant": ["guardian", "acting on behalf", "legal guardian"],
    "book_lost": ["book is lost", "lost the book", "lost my green book"],
    "card_lost_or_damaged": ["card is lost", "lost my card", "damaged card", "card is damaged"],
    "passport_lost_or_stolen": ["lost my passport", "passport was stolen", "passport lost", "stolen passport", "lost", "stolen"],
    "one_parent_unavailable": ["one parent", "father is absent", "mother is absent", "other parent unavailable", "father unavailable", "mother unavailable"],
    "taking_stepparent_surname": ["stepfather", "stepmother", "stepparent"],
    "follows_parents_marriage": ["after we got married", "following the marriage"],
    "guardianship_or_adoption": ["adoption", "adopted", "guardianship"],
    "consent_unavailable_disputed_or_court_decided": ["consent is disputed", "won't consent", "refuses to consent", "court decided", "court ordered"],
    "surname_holder_consent_relevant": ["consent from", "permission from"],
}


def _detect_complications(applicable_ids: list[str], message: str) -> set[str]:
    text = message.lower()
    detected = set()
    for comp_id in applicable_ids:
        keywords = _COMPLICATION_KEYWORDS.get(comp_id, [])
        if any(kw in text for kw in keywords):
            detected.add(comp_id)
    return detected


# ---------------------------------------------------------------------------
# Groq client + low-level call seams. Tests monkeypatch _call_groq_json and
# _call_groq_text directly rather than mocking the SDK client, mirroring
# how tests/test_api.py monkeypatches routes._detection_fn.
# ---------------------------------------------------------------------------

_groq_client: "Groq | None" = None
_groq_client_checked = False


def _get_groq_client() -> "Groq | None":
    global _groq_client, _groq_client_checked
    if _groq_client_checked:
        return _groq_client
    _groq_client_checked = True
    if Groq is None:
        logger.info("groq package not installed; home_affairs_guide will use the deterministic path only.")
        return None
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        logger.info("GROQ_API_KEY not set; home_affairs_guide will use the deterministic path only.")
        return None
    _groq_client = Groq(api_key=api_key)
    return _groq_client


def reset_groq_client() -> None:
    """Test hook: clears the cached client so a test can toggle GROQ_API_KEY
    and observe the effect."""
    global _groq_client, _groq_client_checked
    _groq_client = None
    _groq_client_checked = False


def _call_groq_json(system_prompt: str, user_prompt: str) -> dict[str, Any] | None:
    """Deterministic-mode, JSON-structured Groq call. Returns the parsed
    object, or None on any failure (missing client, API error, timeout,
    malformed JSON) — callers must treat None as "fall back"."""
    client = _get_groq_client()
    if client is None:
        return None
    try:
        completion = client.chat.completions.create(
            model=_GROQ_MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0,
            response_format={"type": "json_object"},
            timeout=_GROQ_TIMEOUT_SECONDS,
        )
        content = completion.choices[0].message.content
        return json.loads(content)
    except Exception:
        logger.warning("Groq JSON classification call failed; falling back to deterministic logic", exc_info=True)
        return None


def _call_groq_text(system_prompt: str, user_prompt: str) -> str | None:
    """Deterministic-mode, free-text Groq call (used for phrasing only).
    Returns the text, or None on any failure."""
    client = _get_groq_client()
    if client is None:
        return None
    try:
        completion = client.chat.completions.create(
            model=_GROQ_MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0,
            timeout=_GROQ_TIMEOUT_SECONDS,
        )
        return completion.choices[0].message.content
    except Exception:
        logger.warning("Groq phrasing call failed; falling back to deterministic template", exc_info=True)
        return None


# ---------------------------------------------------------------------------
# Groq classification — constrained to an exact enum pulled from the
# reference JSON at call time. Any output outside that enum (or the
# explicit 'unclear' escape hatch) is rejected, not used.
# ---------------------------------------------------------------------------


def _groq_classify_single(context: str, message: str, options: dict[str, str]) -> str | None:
    """options is {id: human-readable label}, both taken live from the
    reference JSON. Returns a validated id, or None (unclear / invalid /
    API failure — all treated identically: fall back)."""
    if not options:
        return None
    system_prompt = (
        f"{context} You may ONLY select from the provided list. If nothing matches, "
        "or you are unsure, return 'unclear' — do not guess. Respond with a JSON "
        "object of the exact shape {\"category\": \"<id from the list below, or 'unclear'>\"}. "
        f"Valid options (id: description): {json.dumps(options)}."
    )
    result = _call_groq_json(system_prompt, f"User message: {message}")
    if result is None:
        return None
    category = result.get("category")
    if category == "unclear":
        return None
    if category not in options:
        logger.warning("Groq returned an unrecognized category %r (valid: %r); treating as unclear", category, list(options))
        return None
    return category


def _groq_classify_multiple(context: str, message: str, options: dict[str, str]) -> set[str] | None:
    """Multi-select variant for complications. Returns a validated subset
    of options.keys() (possibly empty — "none apply" is a valid answer),
    or None on failure/invalid output."""
    if not options:
        return set()
    system_prompt = (
        f"{context} Select ALL that apply from the provided list — zero, one, or more "
        "may apply. You may ONLY select ids from the provided list; never invent a new "
        "one. Respond with a JSON object of the exact shape "
        "{\"complications\": [\"<zero or more ids from the list below>\"]}. "
        f"Valid options (id: description): {json.dumps(options)}."
    )
    result = _call_groq_json(system_prompt, f"User message: {message}")
    if result is None:
        return None
    selected = result.get("complications")
    if not isinstance(selected, list):
        logger.warning("Groq complications response was not a list: %r", selected)
        return None
    if any(item not in options for item in selected):
        logger.warning("Groq returned an unrecognized complication in %r (valid: %r); falling back", selected, list(options))
        return None
    return set(selected)


def _resolve_service(message: str, reference: dict[str, Any]) -> str | None:
    options = {sid: s["display_name"] for sid, s in reference["services"].items()}
    result = _groq_classify_single(
        "You are classifying which South African Home Affairs service a user's message is about.",
        message, options,
    )
    if result is not None:
        return result
    logger.info("Falling back to keyword classifier for service classification")
    return _classify_service(message)


def _resolve_sub_case(service_id: str, message: str, reference: dict[str, Any]) -> str | None:
    service = reference["services"][service_id]
    options = {scid: sc["label"] for scid, sc in service["sub_cases"].items()}
    question = _SUB_CASE_QUESTIONS.get(service_id, "")
    result = _groq_classify_single(
        f"You are classifying which sub-case of the '{service['display_name']}' Home Affairs "
        f"service a user's message is about. The user was just asked: {question!r}",
        message, options,
    )
    if result is not None:
        return result
    logger.info("Falling back to keyword classifier for sub_case classification (service=%s)", service_id)
    return _classify_sub_case(service_id, message)


def _resolve_situation(message: str, reference: dict[str, Any]) -> str | None:
    situations = reference["services"]["smart_id"]["sub_cases"]["renewal_or_replacement"]["situations"]
    options = {sid: s["label"] for sid, s in situations.items()}
    result = _groq_classify_single(
        "You are classifying which Smart ID renewal/replacement situation a user's message describes.",
        message, options,
    )
    if result is not None:
        return result
    logger.info("Falling back to keyword classifier for smart_id situation classification")
    return _classify_smart_id_situation(message)


def _resolve_complications(applicable_ids: list[str], message: str, documents_source: dict[str, Any]) -> set[str]:
    conditional = documents_source.get("conditional_documents", {})
    options = {cid: conditional[cid]["trigger_label"] for cid in applicable_ids if cid in conditional}
    result = _groq_classify_multiple(
        "You are identifying which complications, if any, apply to the user's situation.",
        message, options,
    )
    if result is not None:
        return result
    logger.info("Falling back to keyword matcher for complications detection")
    return _detect_complications(applicable_ids, message)


# ---------------------------------------------------------------------------
# Deterministic checklist assembly — reads only the reference JSON, never
# generates a document/fee/fact that isn't there. Unaffected by Groq: this
# section runs identically whether or not Groq is available.
# ---------------------------------------------------------------------------


def _resolve_documents_source(state: ConversationState, sub_case: dict[str, Any]) -> dict[str, Any]:
    """The dict holding 'documents'/'base_documents' + 'conditional_documents'
    for the current state — a situation for smart_id renewals, else the
    sub_case itself."""
    if state.service_id == "smart_id" and state.sub_case_id == "renewal_or_replacement":
        return sub_case["situations"][state.situation_id]
    return sub_case


def _applicable_complication_ids(state: ConversationState, sub_case: dict[str, Any]) -> list[str]:
    src = _resolve_documents_source(state, sub_case)
    return list(src.get("conditional_documents", {}).keys())


def _collect_documents(state: ConversationState, sub_case: dict[str, Any]) -> tuple[list[dict[str, Any]], str | None]:
    src = _resolve_documents_source(state, sub_case)
    documents = list(src.get("documents") or src.get("base_documents") or [])
    conditional = src.get("conditional_documents", {})
    for comp_id in state.complications:
        block = conditional.get(comp_id)
        if block:
            documents.extend(block["documents"])
    return documents, src.get("process_note")


def _format_document_line(item: dict[str, Any]) -> str:
    tail: list[str] = []
    if item.get("issuer"):
        tail.append(f"from {item['issuer']}")

    flags: list[str] = []
    if item.get("original_required") is True:
        flags.append("original required")
    elif item.get("original_required") is False:
        flags.append("original not required")
    if item.get("certified_copy_acceptable") is True:
        flags.append("certified copy acceptable")
    if item.get("personal_attendance_required") is True:
        flags.append("personal attendance required")
    if item.get("biometrics_required") is True:
        flags.append("biometrics required")
    if flags:
        tail.append(", ".join(flags))

    if item.get("applies_when"):
        tail.append(f"applies when {item['applies_when']}")
    if item.get("note"):
        tail.append(item["note"])

    fee = item.get("fee")
    if fee:
        amount = fee.get("amount") or "a fee"
        verify = " (verify before demo — tariffs may change)" if fee.get("verify_before_demo") else ""
        tail.append(f"fee: {amount}{verify}")

    line = item["document"]
    if tail:
        line += " — " + "; ".join(tail)
    return line


_SOURCE_REF_CAUTIONS: dict[str, str] = {
    "affidavit": (
        "Affidavits: ask the specific office whether commissioning is free; never pay an "
        "unofficial fee. SAPS is a reliably free source; banks, post offices, and attorneys may charge."
    ),
    "certified_copy_of_id": (
        "Certified copies: availability and cost can differ by office — take the original document with you."
    ),
    "birth_certificate_reissue": (
        "Birth certificate re-issues: confirm the current fee with Home Affairs — don't assume a fixed tariff."
    ),
}


def _trailing_source_cautions(documents: list[dict[str, Any]]) -> list[str]:
    seen: set[str] = set()
    notes: list[str] = []
    for doc in documents:
        for ref in doc.get("source_refs", []):
            if ref in _SOURCE_REF_CAUTIONS and ref not in seen:
                seen.add(ref)
                notes.append(_SOURCE_REF_CAUTIONS[ref])
    return notes


def _format_cost(cost: dict[str, Any] | None) -> str:
    if cost is None:
        return "Not specified in our reference material — confirm the current fee with Home Affairs."
    amount = cost.get("amount") or "A fee applies"
    verify = " (verify before demo — tariffs may change)" if cost.get("verify_before_demo") else ""
    note = f" — {cost['note']}" if cost.get("note") else ""
    return f"{amount}{verify}{note}"


_ESTIMATED_TIME_NOTE = "Not specified in our reference material — confirm processing times with Home Affairs."


# ---------------------------------------------------------------------------
# Phrasing — Groq rephrases the exact grounding payload; any ungrounded
# output falls back to the deterministic template. documentsNeeded is
# never touched by this step; only the conversational `reply` text is.
# ---------------------------------------------------------------------------

_FEE_NUMBER_PATTERN = re.compile(r"R\s?\d+")


def _fee_numbers_in(text: str) -> set[str]:
    return {m.group().replace(" ", "").upper() for m in _FEE_NUMBER_PATTERN.finditer(text)}


def _build_grounding_payload(
    service: dict[str, Any],
    sub_case: dict[str, Any],
    documents: list[dict[str, Any]],
    cost: dict[str, Any] | None,
    process_note: str | None,
    general_disclaimer: str,
    cautions: list[str],
) -> dict[str, Any]:
    return {
        "service": service["display_name"],
        "sub_case": sub_case["label"],
        "documents": [
            {
                "document": d["document"],
                "issuer": d.get("issuer"),
                "original_required": d.get("original_required"),
                "certified_copy_acceptable": d.get("certified_copy_acceptable"),
                "personal_attendance_required": d.get("personal_attendance_required"),
                "biometrics_required": d.get("biometrics_required"),
                "applies_when": d.get("applies_when"),
                "note": d.get("note"),
                "fee": d.get("fee"),
            }
            for d in documents
        ],
        "cost": cost,
        "process_note": process_note,
        "disclaimer": sub_case.get("disclaimer"),
        "important_exclusions": sub_case.get("important_exclusions", []),
        "general_disclaimer": general_disclaimer,
        "cautions": cautions,
    }


def _allowed_fee_numbers(payload: dict[str, Any]) -> set[str]:
    allowed: set[str] = set()
    cost = payload.get("cost")
    if cost and cost.get("amount"):
        allowed |= _fee_numbers_in(cost["amount"])
    for doc in payload.get("documents", []):
        fee = doc.get("fee")
        if fee and fee.get("amount"):
            allowed |= _fee_numbers_in(fee["amount"])
    return allowed


_FEE_UNCERTAINTY_PHRASES = (
    "needs to be confirmed", "need to confirm", "confirm the fee", "verify the fee",
    "not sure of the fee", "check the fee", "fee is unclear", "unclear fee",
    "confirm this fee", "fee needs confirming", "confirm the cost", "cost needs confirming",
    "cost is unclear", "confirm what the fee",
)


def _phrasing_implies_false_fee_uncertainty(phrased_text: str, payload: dict[str, Any]) -> bool:
    """Catches the inverse of a hallucinated number: claiming a fee "needs
    confirming" when the source data states it plainly instead
    (verify_before_demo is False, e.g. "Generally free"). Only fires when
    the data is actually certain, so it never flags a genuine
    verify_before_demo=True case."""
    cost = payload.get("cost")
    if not cost or cost.get("verify_before_demo") is not False:
        return False
    text = phrased_text.lower()
    return any(phrase in text for phrase in _FEE_UNCERTAINTY_PHRASES)


def _phrasing_is_grounded(phrased_text: str, payload: dict[str, Any]) -> bool:
    """The automated safety checks on Groq's phrasing: (1) any currency
    figure it states must already appear in the grounding payload, and
    (2) it must not claim a fee "needs confirming" when the data states
    one plainly. Document names/issuers are never at risk of drifting —
    documentsNeeded is always rendered deterministically by
    _format_document_line from the same payload, never by Groq."""
    if not _fee_numbers_in(phrased_text).issubset(_allowed_fee_numbers(payload)):
        return False
    if _phrasing_implies_false_fee_uncertainty(phrased_text, payload):
        return False
    return True


_PHRASING_SYSTEM_PROMPT = (
    "You are writing a warm, conversational reply for a South African Home Affairs "
    "guidance chatbot. Rephrase ONLY the information provided below. Do not add, "
    "infer, or supplement any document, fee, form number, or process detail that is "
    "not explicitly present in this data. If the data says a fee needs confirming "
    "(verify_before_demo is true), say that — do not state a number. If the data "
    "states a cost plainly with nothing to verify (verify_before_demo is false, e.g. "
    "'Generally free'), state it plainly too — do not imply uncertainty and do not "
    "say it needs confirming. Do not mention any service or sub-case other than the "
    "one described below. Keep it to a short paragraph — the itemised document "
    "checklist itself is shown separately, so don't repeat it as a list."
)


def _groq_phrase(payload: dict[str, Any]) -> str | None:
    user_prompt = "Checklist data (the ONLY source of facts you may use):\n" + json.dumps(payload, indent=2)
    return _call_groq_text(_PHRASING_SYSTEM_PROMPT, user_prompt)


def _deterministic_reply_text(
    service: dict[str, Any],
    sub_case: dict[str, Any],
    process_note: str | None,
    general_disclaimer: str,
    cautions: list[str],
) -> str:
    reply_parts = [f"Here's what you'll typically need for {service['display_name']} — {sub_case['label']}:"]
    if process_note:
        reply_parts.append(process_note)
    if sub_case.get("disclaimer"):
        reply_parts.append(sub_case["disclaimer"])
    for exclusion in sub_case.get("important_exclusions", []):
        reply_parts.append(exclusion)
    reply_parts.append(general_disclaimer)
    reply_parts.extend(cautions)
    return " ".join(reply_parts)


def _build_final_reply(
    service: dict[str, Any],
    sub_case: dict[str, Any],
    documents: list[dict[str, Any]],
    cost: dict[str, Any] | None,
    process_note: str | None,
    general_disclaimer: str,
    cautions: list[str],
) -> str:
    payload = _build_grounding_payload(service, sub_case, documents, cost, process_note, general_disclaimer, cautions)
    phrased = _groq_phrase(payload)
    if phrased is not None:
        if _phrasing_is_grounded(phrased, payload):
            return phrased
        logger.warning(
            "Groq phrasing failed the fee-grounding check; falling back to deterministic template. Phrased text: %r",
            phrased,
        )
    return _deterministic_reply_text(service, sub_case, process_note, general_disclaimer, cautions)


# ---------------------------------------------------------------------------
# Response builders
# ---------------------------------------------------------------------------


def _question_response(reply: str) -> dict[str, Any]:
    return {
        "reply": reply,
        "documentsNeeded": [],
        "estimatedCost": "",
        "estimatedTime": "",
        "nearestBranch": None,
    }


def _clarify_service_response() -> dict[str, Any]:
    return _question_response(
        "I can help with 4 Home Affairs services: birth registration, Smart ID, passport, "
        "or a name/surname amendment. Which one do you need help with? I don't have "
        "information outside these four services."
    )


_SUB_CASE_QUESTIONS: dict[str, str] = {
    "birth_registration": "Is this within 30 days of the birth, or more than 30 days (late registration)?",
    "smart_id": "Is this a first Smart ID application (age 16+), or a renewal/replacement of an existing ID?",
    "passport": "Is this for an adult, a child under 16, a child under 18, or are you applying from outside South Africa?",
    "name_surname_amendment": (
        "What kind of name change is it — a spelling/administrative error, a marriage-related "
        "change, divorce or widowhood, a child's surname, or an adult assuming an unrelated surname?"
    ),
}


def _clarify_sub_case_response(service_id: str) -> dict[str, Any]:
    return _question_response(_SUB_CASE_QUESTIONS[service_id])


def _clarify_situation_response() -> dict[str, Any]:
    return _question_response(
        "Which situation applies: replacing a green ID book, replacing a Smart ID, a lost or "
        "stolen document, a minor applicant, a parent who is deceased, a marital-status change, "
        "or a pending name/surname amendment?"
    )


def _clarify_complications_response(applicable_ids: list[str], state: ConversationState, sub_case: dict[str, Any]) -> dict[str, Any]:
    src = _resolve_documents_source(state, sub_case)
    conditional = src.get("conditional_documents", {})
    labels = [conditional[cid]["trigger_label"] for cid in applicable_ids if cid in conditional]
    reply = "Do any of these apply to you? " + "; ".join(labels) + ". If none apply, just say 'no'."
    return _question_response(reply)


def _not_covered_response(sub_case: dict[str, Any]) -> dict[str, Any]:
    return _question_response(sub_case["message"])


def _final_response(state: ConversationState, reference: dict[str, Any], service: dict[str, Any], sub_case: dict[str, Any]) -> dict[str, Any]:
    documents, process_note = _collect_documents(state, sub_case)
    lines = [_format_document_line(d) for d in documents]
    cautions = _trailing_source_cautions(documents)
    cost = sub_case.get("cost")

    reply = _build_final_reply(service, sub_case, documents, cost, process_note, reference["general_disclaimer"], cautions)

    return {
        "reply": reply,
        "documentsNeeded": lines,
        "estimatedCost": _format_cost(cost),
        "estimatedTime": _ESTIMATED_TIME_NOTE,
        "nearestBranch": None,
    }


# ---------------------------------------------------------------------------
# Entry point — matches routes.py's _CHAT_CANDIDATE_FN_NAMES binding contract.
# ---------------------------------------------------------------------------


def answer(message: str, location: dict[str, Any] | None = None, conversation_id: str | None = None) -> dict[str, Any]:
    """Classify + advance the conversation one step, returning a response
    shaped {reply, documentsNeeded, estimatedCost, estimatedTime,
    nearestBranch, conversationId}.
    """
    resolved_conversation_id = conversation_id or str(uuid.uuid4())
    key = _session_key(conversation_id)
    state = _SESSIONS.get(key) or ConversationState()

    reference = load_reference()

    def respond(resp: dict[str, Any]) -> dict[str, Any]:
        resp["conversationId"] = resolved_conversation_id
        return resp

    if state.stage == "service":
        service_id = _resolve_service(message, reference)
        if service_id is None:
            _SESSIONS[key] = state
            return respond(_clarify_service_response())
        state.service_id = service_id
        state.stage = "sub_case"

    service = reference["services"][state.service_id]

    if state.stage == "sub_case":
        sub_case_id = _resolve_sub_case(state.service_id, message, reference)
        if sub_case_id is None:
            _SESSIONS[key] = state
            return respond(_clarify_sub_case_response(state.service_id))
        state.sub_case_id = sub_case_id
        sub_case = service["sub_cases"][sub_case_id]
        if sub_case.get("not_covered"):
            _SESSIONS.pop(key, None)
            return respond(_not_covered_response(sub_case))
        state.stage = "situation" if (state.service_id == "smart_id" and sub_case_id == "renewal_or_replacement") else "complications"

    sub_case = service["sub_cases"][state.sub_case_id]

    if state.stage == "situation":
        situation_id = _resolve_situation(message, reference)
        if situation_id is None:
            _SESSIONS[key] = state
            return respond(_clarify_situation_response())
        state.situation_id = situation_id
        state.stage = "complications"

    applicable = _applicable_complication_ids(state, sub_case)

    if state.stage == "complications":
        if not applicable:
            state.stage = "done"
        else:
            state.stage = "awaiting_complications_answer"
            _SESSIONS[key] = state
            return respond(_clarify_complications_response(applicable, state, sub_case))

    if state.stage == "awaiting_complications_answer":
        documents_source = _resolve_documents_source(state, sub_case)
        state.complications |= _resolve_complications(applicable, message, documents_source)
        state.stage = "done"

    _SESSIONS.pop(key, None)
    return respond(_final_response(state, reference, service, sub_case))
